#!/bin/sh
# Copyright 2011 Brent Longborough
# Please read gitinfo.pdf for licencing and other details
# -----------------------------------------------------
# Post-{commit,checkout,merge} hook for the gitinfo package
#
for pref in ./ ./* ./*/* ./*/*/*
do
    if [ -d "$pref" ]
    then
	git log -1 --date=local \
	    --pretty=format:"\usepackage[%
			shash={%h},
			lhash={%H},
			authname={%an},
			authemail={%ae},
			authsdate={%ad},
			authidate={%ai},
			authudate={%at},
			commname={%an},
			commemail={%ae},
			commsdate={%ad},
			commidate={%ai},
			commudate={%at},
			refnames={%d}
		]{gitsetinfo}" $pref > $pref/gitHeadInfo.gin 2>/dev/null
    fi
done
